<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static count()
 * @method static first()
 * @method static create(array $only)
 */
class MissionAndValue extends Model
{
    use HasFactory;

    protected $fillable = [
        'description_1',
        'description_2',
        'background_img',
        'created_by',
        'updated_by',
    ];

    const PERMISSION = [
        1 => 'create',
        2 => 'edit',
    ];

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    public function updatedUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }
    public function createdUser()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($setting){
            $setting->created_by = Auth::id();
        });
        static::updating(function ($setting){
            $setting->updated_by = Auth::id();
        });
    }
}
