<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * @method static first()
 * @method static count()
 * @method static create(array $only)
 */
class Portfolio extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'description',
        'sub_title',
        'created_by',
        'updated_by',
    ];

    const PERMISSION = [
        1 => 'create',
        2 => 'edit',
        3 => 'delete',
    ];

    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    public function updatedUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }
    public function createdUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($setting){
            $setting->created_by = Auth::id();
        });
        static::updating(function ($setting){
            $setting->updated_by = Auth::id();
        });
    }
}
