<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

/**
 * @method static create(array $onlyGo)
 * @method static status()
 * @method static latest()
 * @method static first()
 * @method static count()
 */
class Setting extends Model
{
    use HasFactory;

    protected $fillable = [
        'site_name',
        'updated_by',
    ];


    const PERMISSION = [
        1 => 'create',
        2 => 'edit',
    ];

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    public function updatedUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::updating(function ($setting){
            $setting->updated_by = Auth::id();
        });
    }
}
