<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class TalentReply extends Model
{
    use HasFactory;
    protected $fillable = [
        'talent_id',
        'talent_email',
        'subject',
        'message_body',
    ];

    public function createdUser(){
        return $this->belongsTo(User::class, 'created_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($reply) {
            $reply->created_by = Auth::id() ?? 1;
        });
    }
}
